name: medtrack
description: "A medication reminder app with Firebase integration."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  intl: ^0.18.1
  fluttertoast: ^8.2.1
  firebase_storage: ^11.2.4
  image_picker: ^0.8.7+3
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/notification_sound.mp3.wav
    
