// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5xOqbJ8YYLwBIqxyTt0xRYopgTu6nYc',
    appId: '1:890415376594:web:d8c0c9a3a3ca20be13650b',
    messagingSenderId: '890415376594',
    projectId: 'medtrackf',
    authDomain: 'medtrackf.firebaseapp.com',
    storageBucket: 'medtrackf.firebasestorage.app',
    measurementId: 'G-85L722ZKMM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApi_uFvMiiefgqemIognuL8_Mi5E3cRi8',
    appId: '1:890415376594:ios:883394350624b6cd13650b',
    messagingSenderId: '890415376594',
    projectId: 'medtrackf',
    storageBucket: 'medtrackf.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApi_uFvMiiefgqemIognuL8_Mi5E3cRi8',
    appId: '1:890415376594:ios:883394350624b6cd13650b',
    messagingSenderId: '890415376594',
    projectId: 'medtrackf',
    storageBucket: 'medtrackf.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5xOqbJ8YYLwBIqxyTt0xRYopgTu6nYc',
    appId: '1:890415376594:web:4bfe515c2ef9a79413650b',
    messagingSenderId: '890415376594',
    projectId: 'medtrackf',
    authDomain: 'medtrackf.firebaseapp.com',
    storageBucket: 'medtrackf.firebasestorage.app',
    measurementId: 'G-TEF2K73M3T',
  );
}
